#!/usr/bin/env node
/**
 * Generates packages/ai/generated/version.ts from package.json "version".
 *
 * The generated file is COMMITTED (not gitignored) so typecheck/test/build all
 * see a valid module before the build's prebuild hook runs -- ci.yml runs
 * `typecheck` and `test` around `build`, and index.ts re-exports VERSION from
 * here. `prebuild` re-runs this so the published dist always carries the real
 * version. The doc-parity `check-version` gate asserts the committed value and
 * the package.json value agree, and that index.ts re-exports (no hardcoded
 * literal). Born from the 1.0.0-vs-3.2.x drift (dcyfr-ai-doc-automation Wave 0).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptsDir, '..');

export const packageVersion = JSON.parse(
  readFileSync(join(repoRoot, 'package.json'), 'utf8'),
).version;

export const generatedVersionPath = join(
  repoRoot,
  'packages',
  'ai',
  'generated',
  'version.ts',
);

export function renderVersionModule(version) {
  return (
    '// GENERATED by scripts/gen-version.mjs -- do not edit.\n' +
    '// Source of truth: package.json "version".\n' +
    `export const VERSION = '${version}';\n`
  );
}

function main() {
  mkdirSync(dirname(generatedVersionPath), { recursive: true });
  writeFileSync(generatedVersionPath, renderVersionModule(packageVersion));
  console.log(
    `gen-version: wrote VERSION='${packageVersion}' -> packages/ai/generated/version.ts`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
