#!/usr/bin/env node
/**
 * Generates config artifacts from the Zod FrameworkConfigSchema (the single
 * source of truth):
 *   - config/schema.json         -- machine-readable JSON Schema (Zod v4 z.toJSONSchema)
 *   - docs/CONFIG_REFERENCE.md    -- generated top-level key table
 *
 * It deliberately does NOT regenerate config/default.{json,yaml} -- those are
 * curated onboarding templates richer than bare schema defaults. The
 * config-parity gate coverage-checks them instead (every schema-default key must
 * be present). Imports the COMPILED schema, so it runs after `npm run build`.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { FrameworkConfigSchema } from '../../dist/ai/config/schema.js';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');
const SCHEMA_ID = 'https://dcyfr.ai/schema/config.json';

/** Replace any value equal to the absolute cwd (project.root default) with '.'. */
function normalizeCwd(obj, cwd) {
  if (Array.isArray(obj)) obj.forEach((v) => normalizeCwd(v, cwd));
  else if (obj && typeof obj === 'object') {
    for (const k of Object.keys(obj)) {
      if (obj[k] === cwd) obj[k] = '.';
      else normalizeCwd(obj[k], cwd);
    }
  }
}

function typeOf(p) {
  if (!p || typeof p !== 'object') return 'unknown';
  if (p.$ref) return 'object';
  if (p.type) return Array.isArray(p.type) ? p.type.join(' \\| ') : p.type;
  if (p.anyOf) return [...new Set(p.anyOf.map(typeOf))].join(' \\| ');
  if (p.oneOf) return [...new Set(p.oneOf.map(typeOf))].join(' \\| ');
  if (p.enum) return 'enum';
  if (p.properties) return 'object';
  return 'object';
}

function defaultOf(p) {
  if (!p || !('default' in p)) return '(none)';
  const d = p.default;
  if (d === null) return '`null`';
  if (Array.isArray(d)) return d.length ? '`[...]`' : '`[]`';
  if (typeof d === 'object') return '`{...}`';
  return '`' + String(JSON.stringify(d)).replace(/\|/g, '\\|') + '`';
}

export function buildArtifacts() {
  // Pin the JSON Schema dialect explicitly so a future zod patch bump can't
  // silently change the default target and break the byte-identical config gate.
  const jsonSchema = z.toJSONSchema(FrameworkConfigSchema, { target: 'draft-2020-12' });
  normalizeCwd(jsonSchema, process.cwd());
  jsonSchema.$id = SCHEMA_ID;
  const schemaJson = JSON.stringify(jsonSchema, null, 2) + '\n';

  const props = jsonSchema.properties || {};
  const required = new Set(jsonSchema.required || []);
  const keys = Object.keys(props).sort();
  const rows = keys.map(
    (k) => `| \`${k}\` | ${typeOf(props[k])} | ${required.has(k) ? 'yes' : 'no'} | ${defaultOf(props[k])} |`,
  );

  const configReferenceMd = [
    '# Configuration Reference',
    '',
    '<!-- GENERATED by scripts/doc-parity/gen-config.mjs from packages/ai/config/schema.ts. Do not edit by hand; run `npm run docs:gen:config`. -->',
    '',
    'Top-level keys of the framework configuration (`FrameworkConfigSchema`). The',
    'machine-readable JSON Schema is at [`config/schema.json`](../config/schema.json),',
    'and ready-to-copy templates live in [`config/`](../config/).',
    '',
    '| Key | Type | Required | Default |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');

  let defaultKeys;
  try {
    defaultKeys = Object.keys(FrameworkConfigSchema.parse({}));
  } catch {
    defaultKeys = keys.filter((k) => required.has(k) || 'default' in (props[k] || {}));
  }

  return { schemaJson, configReferenceMd, topLevelKeys: keys, defaultKeys };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { schemaJson, configReferenceMd } = buildArtifacts();
  writeFileSync(join(repoRoot, 'config', 'schema.json'), schemaJson);
  writeFileSync(join(repoRoot, 'docs', 'CONFIG_REFERENCE.md'), configReferenceMd);
  console.log('gen-config: wrote config/schema.json + docs/CONFIG_REFERENCE.md');
}
